# Generated by Django 5.0.14 on 2026-05-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='allow_member_messages',
            field=models.BooleanField(default=True),
        ),
    ]
